### ISSUE TITLE
Enhancement (FastConnect)

### ISSUE THREAD

**Issue by CrazyWords1** [VelocityPowered/Velocity#162]
Support [FastConnect](https://www.spigotmc.org/resources/fastconnect.26795/) by default on Velocity

**Comment by electronicboy** [comment]
FastConnect is such a gross hack that it's pretty much guaranteed to cause issues, you basically add much more work for the proxy to do, and you would require velocity to support entity remapping, which /will/ break a lot of the many aims of velocity

**Comment by astei** [comment]
It would be nice, but it will create far more work on our already small contributor base and team, since we would have to perform entity ID rewriting, and the whole goal of the project is to avoid that!

For this reason, we can't do this. Sorry.

**Comment by Leymooo** [comment]
Fast connect causes many issues. Like a memory leak on client, entities disappearing, etc. For solve this problem we need to store loaded chunks(only x and z), and entities(only entity id), and on server switch we need to unload chunks and despawn entities. But this is not worth it, because fastconnect does not speedup a server switch very much (like a 10-20% faster).

**Comment by CrazyWords1** [comment]
Oh okey

**Comment by mikroskeem** [comment]
Also FastConnect introduces really annoying artifacts when you switch from normal world server to clean world server (e.g survival -> skyblock).

**Comment by Leymooo** [comment]
only when switch to same coordinates.
