### ISSUE TITLE
NettyHttpClient meet a error if request url is non 443 port https

### ISSUE THREAD

**Issue by PonyPC** [VelocityPowered/Velocity#172]
I modify the MOJANG_HASJOINED_URL to a ssl proxy cause the network issue in my country.
And NettyHttpClient treat 'https://example.com:4443/path/to/' as a http connection, I think this area should modify to determinate https connection by protocol instead of port.
```
          @Override
          public void channelCreated(Channel channel) throws Exception {
            if (key.getPort() == 443) {
            //something like: if (key.getProtocol().equals("https")) {
              SslContext context = SslContextBuilder.forClient().protocols("TLSv1.2").build();
              // Unbelievably, Java doesn't automatically check the CN to make sure we're talking
              // to the right host! Therefore, we provide the intended host name and port, along
              // with asking Java very nicely if it could check the hostname in the certificate
              // for us.
              SSLEngine engine = context.newEngine(channel.alloc(), key.getHostString(),
                  key.getPort());
              engine.getSSLParameters().setEndpointIdentificationAlgorithm("HTTPS");
              channel.pipeline().addLast("ssl", new SslHandler(engine));
            }
            channel.pipeline().addLast("http", new HttpClientCodec());
          }
```

**Comment by astei** [comment]
I don't necessarily consider this an issue with Velocity. The `NettyHttpClient` exists primarily for our convenience, and as long as it does the job it should for our purposes, then it's not really our problem.

You've modified the source code (in this case, to inject a custom authentication URL). While we didn't handle this case correctly, it's also not strictly our responsibility to fix. I have fixed the issue anyway, because the prior behavior was suboptimal and incorrect.

**Comment by PonyPC** [comment]
Anyway, thanks for your hard working!
