### ISSUE TITLE
Centos 7 server start issues

### ISSUE THREAD

**Issue by MisterPie314** [VelocityPowered/Velocity#260]
I tried to follow the guide and use java -jar velocity-proxy-1.0.3-all.jar but this error popped up

.
![e08255b6897dcd576343a77b02e95243](https://user-images.githubusercontent.com/15909561/69881575-762b4700-129b-11ea-95d1-d56d104c184b.png)

**Comment by electronicboy** [comment]
Your /tmp partition is mounted as noexec, meaning that it can't extract the
native libraries for netty, it should still work, just you'll be missing
out on performance gains;

There is a system property to override where these will be extracted to,
bit the easiest solution is to allow things to be executed on /tmp, as many
things basically expect to be able to put their natives there, e.g. Netty,
sqlite

**Comment by astei** [comment]
I would strongly advise against having `/tmp` mounted as `noexec` because it _will_ break certain plugins. I have committed a fix that permits Velocity to start when the temporary directory is mounted as `noexec` by falling back on the unoptimized Java natives.

**Comment by kevhawk2914** [comment]
Should keep in mind that distro such as RHEL (Centos) are all starting to move towards noexec /tmp as a security measure.

**Comment by astei** [comment]
As a more complete fix, I've introduced a system property `velocity.natives-tmpdir` that allows you to extract the natives in a different directory that is marked executable.

Note that due to limited resources, I only support Velocity's Linux natives on Debian-based distributions and the distribution I personally use (Arch Linux).
