### ISSUE TITLE
Propose: Allow finer event handler prioritization

### ISSUE THREAD

**Issue by robinbraemer** [VelocityPowered/Velocity#271]
Currently we have the choice of just 5 (FIRST, EARLY, NORMAL, LATE, LAST) event post orders.

I propose that we allow event handlers to be registered with a `prioritization` that is an integer.
This allows setting a finer order of handler invokation.

**Comment by astei** [comment]
What use case do you have in mind?

**Comment by robinbraemer** [comment]
A common use case is, when there are say 2 plugins:

- Core plugin
  - has an LoginEvent handler of **priority 100** that initializes a user object from the db into cache that the child handlers/plugins can retrieve
  - has a DisconnectEvent handler of **priority -100** that deletes the user from the cache

- Sessions plugin
  - making sure that in a multi-proxy network a player is connected at most once
  - has a LoginEvent handler of **priority 90** to create a session in the db from the initialized user by the Core
  - has a DisconnectEvent handler of **priority -90** that deletes the session from the db

Now later we decide to add a ban plugin that should:
  - handle LoginEvents after the Core plugin but before the Sessions plugin
    - we need that user object from the core for the _userId_ but don't want to create a new session if the player is banned
  - meaning we just set the ban plugins LoginEvent handler **priority to -95** to get invoked in between

The gives the ability to place event handlers into exact order without knowing what handlers may be added in the future.

In this sample situation the LoginEvent handlers would currently be using `PostOrder.FIRST`
as they are all mission critical handlers that must run before any other plugins login handlers.

**Comment by hugmanrique** [comment]
You only listed two events that need to run before before `NORMAL` priority events, which would fit nicely in`FIRST` and `EARLY` priorities. I doubt there's that many plugins that require more than 2 separate `LoginEvents` that need to run in order before `NORMAL` events.

**Comment by astei** [comment]
Precisely: this proposal right now proposes a breaking change. I'm not categorically opposed to those, but given that the focus is on 1.1.0 (which will not be API-breaking), I'll need a version of this proposal that doesn't involve an API breakage.

**Comment by astei** [comment]
I'm torn. I can see the idea and the desire for this feature, but I'm not fully convinced that this delivers value in general (especially since Spigot nor Sponge really support this - AFAIK, only BungeeCord exposes this, and in general we don't want to do what BungeeCord does blindly!)

Consider myself neutral on this.

**Comment by A248** [comment]
When one new developer writes an event listener in a simple plugin, such developer often does not specify the listener's priority. There is only so much to do about this, and it is beside this issue. However, when the beginner developer who has that bit of experience to know to set a good priority, does so, the entire community benefits.

The developer of a simple plugin need not add hooks for every kind of other plugin which would otherwise listen to the same event. The beauty of the events framework is that it allows one plugin to seamlessly interact with every other which might come after or before it, through the simple manner of cancellation and priority specification; it is not merely concerned with once-modifying a certain aspect of the proxy or server.

But observe - as servers become more complex, and creative developers and server owners program and implement wide varieties of features with dozens of plugins handling remote areas of the server's API - such a small list of priorities to choose from, numbering in the single digits, becomes insufficient. In fact, it becomes dreadfully insufficient. When one plugin is listening on the second-to-last priority, there is room for only one more plugin in the ordering, once such is added, there is no more availability for complexity. All of the sudden the potential which marked the events framework has dried up.

A system should not drastically limit its complexity so. Velocity does not have to be like Spigot or Sponge. It does not have to be confined by a small enum of listener priorities. The Velocity project is a great opportunity to improve on the mistakes of other APIs. Complexity is not a disadvantage; it is an advantage in that it indicates an accomplishment of some other making. A framework should not regard itself by the little convenience such as having an enum of five elements, but by the capaciousness which comes with expanding that enum to hundreds of values, in the form of the beautifully simply yet extraordinarily powerful `int`.

**Comment by astei** [comment]
Implemented as 929d623b
