### ISSUE TITLE
Setup jenkins to build&validate PRs

### ISSUE THREAD

**Issue by MiniDigger** [VelocityPowered/Velocity#86]
see #84 for context

**Comment by astei** [comment]
Our Jenkins instance runs on a 2GB VPS - it barely handles two concurrent builds. There are also security concerns, since the pipeline Docker container has access to the Javadoc and Maven repository.

Perhaps I can configure another Jenkins pipeline that only exposes the bare minimum required and have that be the pipeline used for CI builds.

**Comment by MiniDigger** [comment]
Oh, if resources are an issue, maybe Travis, circle ci, drone ci or whatever could be set up.

**Comment by astei** [comment]
No, the problem isn't resources. The problem is security. I'm including a screenshot from the GitHub branch PRs as evidence:

![image](https://user-images.githubusercontent.com/16436212/45583111-0c876e80-b88a-11e8-80ef-6bf1fa93742c.png)

As this text makes very clear, giving people wanton access to Jenkins is asking for a disaster, especially as we use a declarative pipeline. So we can't do this securely, and I do not want to set up another CI system like Drone at the moment.

**Comment by MiniDigger** [comment]
ah ok, didn't use jenkins in years, I am used to docker based build pipelines like gitlab-ci

**Comment by astei** [comment]
Our setup is Docker based :)

**Comment by astei** [comment]
Sorry, I'm misinterpreting stuff. I got this totally wrong. I was pointing out a tangential (but at at all related) Jenkins setting.

Unfortunately, we have several Docker volumes mounted in the Jenkinsfile and they point to real, live websites (jd.velocitypowered.com and repo.velocitypowered.com). Getting PR pulls and such working seamlessly without risking these two websites will be extremely difficult.

**Comment by astei** [comment]
Update on this: After doing some shuffling around, Jenkins should now be able to automatically build pull requests.
